version: "3.8"

services:
  go-app:
    build:
      context: ./example1-go
    ports:
      - "8080:8080"
    networks:
      - multistage-network

  node-app:
    build:
      context: ./example2-node
    ports:
      - "3000:3000"
    networks:
      - multistage-network

  python-app:
    build:
      context: ./example3-python
    ports:
      - "5001:5000"
    networks:
      - multistage-network

  java-app:
    build:
      context: ./example4-java
    ports:
      - "8081:8080" # Changed to 8081 since Go app uses 8080
    networks:
      - multistage-network

networks:
  multistage-network:
    driver: bridge
